SKILL_MAX_LENGTH = 124
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

SKILLS_AUTOCOMPLETE_LIMIT = 10
PROJECTS_PAG = 12

NAME_MAX_LENGTH = 124
SURNAME_MAX_LENGTH = 124

COLOR_BLUE = "#2768FFD3"
COLOR_RED = "#FF3E3E"
COLOR_GREEN = "#50FF67"
COLOR_YELLOW = "#FFC53F"
COLOR_PURPLE = "#A78BFA"
COLOR_ORANGE = "#FF9244"
COLOR_LIGHT_BLUE = "#2DC7E2"
COLOR_PINK = "#FF3B9D"
COLOR_LIGHT_GREEN = "#BBFF56"
COLOR_LIGHT_ORANGE = "#FFAB67"


AVATAR_COLORS = [
    COLOR_BLUE,
    COLOR_RED,
    COLOR_GREEN,
    COLOR_YELLOW,
    COLOR_PURPLE,
    COLOR_ORANGE,
    COLOR_LIGHT_BLUE,
    COLOR_PINK,
    COLOR_LIGHT_GREEN,
    COLOR_LIGHT_ORANGE,
]
AVATAR_FONT_SIZE = 100
ABOUT_MAX_LENGTH = 256
AVATAR_ANCHOR_X = 0
AVATAR_ANCHOR_Y = 0
AVATAR_SIZE = 200
NAME_MAX_LENGTH = 124
PHONE_MAX_LENGTH = 12
SURNAME_MAX_LENGTH = 124
